language: go
go:
  - 1.14.4
addons:
  apt:
    packages:
      - gtk+3.0
      - libgtk-3-dev
      - xvfb
install:
  - go get ./...
script: make
deploy:
  provider: releases
  file: remotekeyboard
  skip_cleanup: true
  api_key: $GITHUB_TOKEN
  on:
    branch: master
    tags: true
